

CREATE TABLE Babble (
  	id SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  	text VARCHAR(280) NOT NULL,
  	created timestamp DEFAULT CURRENT TIMESTAMP, 
  	creator VARCHAR(20) NOT NULL,
  	PRIMARY KEY (id),
  	FOREIGN KEY (creator) REFERENCES BabbleUser(username) ON DELETE CASCADE
);